name: hive_innovation_shop
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  lottie: ^1.3.0 #for animated svg or json files
  flutter_screenutil: ^5.4.0+1 #for responsive ui
  get: ^4.6.1 #for state management
  device_preview: ^1.0.0 #to test responsive on different devices
  http: ^0.13.4 #for the api request
  flutter_svg: ^1.0.3 #to use custom svg files
  cached_network_image: ^3.2.0 #to show network image
  flutter_rating_bar: ^4.0.0 #FOR THE RATING OUR SERVICE IN APP
  hive_flutter: ^1.1.0
  hive: ^2.1.0 #for offline database
  get_storage: ^2.0.3 #i've been using this To save login token .
  pull_to_refresh: ^2.0.0 #to refresh data



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.10



flutter:


  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
